### ISSUE TITLE
border between the UI elements and webpage

### ISSUE THREAD

**Issue by toxicfox2491** [ashish-kus/MiniSthetic_Firefox#4]
I dont think this is an issue with the theme but do you by chance have some ideas on how I can disable this border?
![image](https://github.com/user-attachments/assets/5476946e-7aa9-44ed-ace9-beadf4ed199a)

**Comment by ashish-kus** [comment]
I'’m trying to solve this but haven’t found a solution yet. I’ll work to fix it as soon as possible.

**Comment by toxicfox2491** [comment]
> I'’m trying to solve this but haven’t found a solution yet. I’ll work to fix it as soon as possible.

thank you!! I really appreciate it

**Comment by ashish-kus** [comment]
@toxicfox2491 Hey buddy i found the solution to this, we have to add some styles in styles/_home.css and we are good to go.

```
~/.mozila/firefox/XXX.defaulr-release-XXX/chrome/styles/_home.css


#tabbrowser-tabbox { 
  outline: none !important;
  box-shadow: none !important;
}

``` 

I will push it soon as working on some major changes in design system.

**Comment by toxicfox2491** [comment]
> @toxicfox2491 Hey buddy i found the solution to this, we have to add some styles in styles/_home.css and we are good to go.
> 
> ```
> ~/.mozila/firefox/XXX.defaulr-release-XXX/chrome/styles/_home.css
> 
> 
> #tabbrowser-tabbox { 
>   outline: none !important;
>   box-shadow: none !important;
> }
> ```
> 
> I will push it soon as working on some major changes in design system.

thank you!! this works!
cant wait to see what you do with the design in the future!
![image](https://github.com/user-attachments/assets/ebc27405-2784-4f31-a938-92a3f276ab3c)
